services:
  frontend:
    build: front_end
    ports:
      - "3000:3000"
    depends_on:
      - app
  app:
    build: app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - model
      - llm_api
  model:
    build: model
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: [ "CMD", "python", "test_script.py" ]
      interval: 10s
      timeout: 5s
      retries: 3
  llm_api:
    build: llm_api
    ports:
      - "8002:8002"
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
volumes:
  mongo-data: